config/routes.rb
Rails.application.routes.draw do
  resource :profile
  root "orders#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
  resources :plates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  waiter     :string
#  board      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
  has_many :plates
  belongs_to :user

  #validations
  validates :board, presence: true
end

app/models/plate.rb
# == Schema Information
#
# Table name: plates
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  price       :decimal(10, 2)
#  available   :boolean
#  order_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Plate < ApplicationRecord
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_one  :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @orders= Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    byebug
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update (order_params)
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_path
  end

private

  def order_params
    params.require(:order).permit(:board, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
  end

  def new
    @profile = Profile.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurante</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li> <%= current_user.email %> </li>
        <li>
       		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
       	</li>
      <% else %>
       	<li>
       	</li>
        <%= link_to('Sign_up', new_user_session_path)  %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
       <% end %>
    </ul>
    </div>
  </div>
</nav>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xs-8">
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <ul>
          <% @order.errors.full_messages.each do |msg|%>
          <li><%= msg.to_s%></li>
        </ul>
        <% end %>
    <% end %>
    <%= f.label :board %>
    <%= f.text_field :board %>
    <%= f.label :user_id %>
    <%= collection_select(:order, :user_id, User.all, :id, :email, prompt: true) %>
    <%= f.submit %>
<% end %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>
<%= render 'form' %>

app/views/orders/index.html.erb
<h2>Ordenes</h2>
<hr>
<%= link_to "Nuevo" , new_order_path %>
</hr>
<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>Mesero</th>
      <th>Mesa</th>
      <th>Detalle</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
    <td><%= order.id %></td>
    <td><%= "nombre" %></td>
    <td><%= order.board %></td>
    <td><%= link_to "D" , order_path(order) %></td>
    <td><%= link_to "E" , edit_order_path(order) %></td>
    <td><%= link_to "X" , order_path(order), method: :delete, data: {confirm: "Estas seguro?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p> </p>
<%= render 'form' %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>
<%= @order.inspect %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
<% if @profile.errors.any? %>
  <ul>
   <%profile.errors.full_messages.each do |msg| %>
   <li> <%= msg.to_s %> </li>
   <% end %>
  </ul>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<h1> Show me the money </h1>
<p> hey </p>

<% if @profile %>
  <%= @profile.inspect %>
  <%= link_to "Editar", edit_profile_path(@profile) %>
<% else %>
  <%= link_to "Crear", new_profile_path %>
<% end %>
<hr>